#06/08/2024

In [1]:
import numpy as np

In [2]:
v=np.ones(10)
v

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
d=np.zeros(9)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
v.size

10

In [5]:
type(v)

numpy.ndarray

In [6]:
v.itemsize

8

In [7]:
v.shape

(10,)

In [8]:
v=np.arange(1,15)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
d=v.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [11]:
w=np.arange(0,50,2).reshape(5,5)
w

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [12]:
e=[1,2,3,4,0,8,9,7,60,0,3,0]
r=np.nonzero(e)
r

(array([ 0,  1,  2,  3,  5,  6,  7,  8, 10]),)

In [13]:
t=np.eye(4)   #Identity matrix
t

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
t=np.diag([9,8,7,6,5,4,32,23,12])
t

array([[ 9,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 32,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 23,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 12]])

In [16]:
y=np.fliplr(t)
y

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  9],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0],
       [ 0,  0, 32,  0,  0,  0,  0,  0,  0],
       [ 0, 23,  0,  0,  0,  0,  0,  0,  0],
       [12,  0,  0,  0,  0,  0,  0,  0,  0]])

In [17]:
u=np.flipud(y)
u

array([[12,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 23,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 32,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9]])

In [18]:
a=np.diag([1,2,3,4,5,6,7],k=4)
a

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
s=np.random.random(5)
s

array([0.85582908, 0.66078499, 0.18247421, 0.34782674, 0.53353524])

In [20]:
d=np.random.random(4)*4
d

array([3.91381862, 1.68818012, 1.41934916, 2.56865305])

In [23]:
f=np.random.randint(9)
f

3

In [24]:
g=np.random.randint(6,size=10)
g

array([2, 5, 5, 1, 0, 2, 1, 4, 3, 0])

In [25]:
h=np.linspace(1,5,10)
h

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
q=np.arange(21)
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [33]:
w=np.array_split(q,7)
w

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14]),
 array([15, 16, 17]),
 array([18, 19, 20])]

In [35]:
e=np.random.choice(["dhoni","virat","vijay","leo","gilla"],size=20)
e

array(['dhoni', 'gilla', 'dhoni', 'dhoni', 'dhoni', 'leo', 'virat',
       'gilla', 'gilla', 'virat', 'vijay', 'leo', 'leo', 'dhoni', 'gilla',
       'virat', 'vijay', 'dhoni', 'gilla', 'dhoni'], dtype='<U5')

In [37]:
a=np.random.choice(["dhoni","virat","vijay","leo","gilla"],size=20,p=[0.5,0.15,0.05,0.15,0.15])
a

array(['dhoni', 'dhoni', 'dhoni', 'dhoni', 'dhoni', 'leo', 'dhoni', 'leo',
       'virat', 'dhoni', 'leo', 'leo', 'dhoni', 'dhoni', 'dhoni', 'dhoni',
       'leo', 'dhoni', 'dhoni', 'leo'], dtype='<U5')

In [40]:
np.random.shuffle(a)
a

array(['dhoni', 'leo', 'leo', 'dhoni', 'dhoni', 'leo', 'dhoni', 'dhoni',
       'dhoni', 'dhoni', 'virat', 'leo', 'dhoni', 'dhoni', 'leo', 'leo',
       'dhoni', 'dhoni', 'dhoni', 'dhoni'], dtype='<U5')